export enum SAGA_ACTIONS {
    ADMIN_FETCH_PRODUCTS = "ADMIN_FETCH-PRODUCTS",
    ADMIN_UPDATE_PRODUCT = "ADMIN_UPDATE_PRODUCT",
    ADMIN_UPATE_COIN = 'ADMIN_UPDATE_COIN',
    ADMIN_WITHDRAW_COIN = "ADMIN_WITHDRAW_COIN",
    ADMIN_FETCH_VAULT = 'ADMIN_FETCH_VAULT'

}